version: "3.9"

services:
  db2:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db2
    ports:
      - "5432:5432"
    volumes:
      - db2_data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      FLIGHT_SERVICE_URL: "http://flight-service:5001"
    depends_on:
      - flight-service

  flight-service:
    build: ./flight-service
    ports:
      - "5001:5001"
    environment:
      DB2_URL: "postgresql+psycopg2://postgres:postgres@db2:5432/db2"
    depends_on:
      - db2

volumes:
  db2_data:



